### ISSUE TITLE
Document @AndroidJsonized

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#106]
Include info about how it determines what type to make the field.

**Comment by Buggaboo** [comment]
Sorry, I don't follow, which field(s)?

**Comment by tobykurien** [comment]
As I understand it, ```@AndroidJsonized``` takes a JSON string and then generates appropriate getters/setters. How does it determine what type the getter should return for each JSON property? Should we provide that information, or does it infer this from the data?

**Comment by Buggaboo** [comment]
It will totally infer everything.

The mapping goes as follows -

There are three primitive JSON scalar types, that map to the following machine types:
* number - long or double
* string - String
* boolean - boolean

and for the aggregate types:
* {} (Object) - maps to a whole new type, named after the key
* [] (List) - maps to a List<SomeType> where SomeType depends on the type of the first element.

There is no limit to the nesting depth.

I suspect that empty lists and objects will blow up the annotation.

mental note: TODO write checks, that give an error (`TransformationContext#addError).
