### ISSUE TITLE
Start work on j2objc cross-platform work

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#107]
Another heads up.

I'm planning on giving some love to the other fruity platform with the closed garden.

I will start a new kitchensink project. I'll probably call it [`xtend-j2objc-template`](https://github.com/Buggaboo/xtend-j2objc-template) or something.

Does anyone have experience with j2objc?

Any caveats?

**Comment by svenefftinge** [comment]
I don't have experience but I wonder why you would prefer j2objc over robovm?

**Comment by Buggaboo** [comment]
Because the client is paying :)

This is not a personal preference btw.

**Comment by Buggaboo** [comment]
Okay, mission accomplished, there are two caveats though.

1. Currently (2016-02-11) [j2objc-gradle](https://github.com/j2objc-contrib/j2objc-gradle) supports gradle <=2.4. Xtendroid supports gradle 2.8, so setup your gradle in two separate gradle environments, one for transpiling xtend to java and one for transpiling java to objc. You can symlink the gradlew file though, but you need two different `gradle/wrapper/gradle-wrapper.properties`, in two different root projects.
2. `sourceSets.main.java.srcDirs += [ 'build/generated/source/xtend/release' ]` add this to the j2objc root project's `build.gradle`

**Comment by Buggaboo** [comment]
Hi Stefan @oehme ,

Do you know how I can use the `org.xtext:xtext-gradle-plugin:${xtext_gradle_ver}` to import deps `org.eclipse.xtend:org.eclipse.xtend.lib:${xtend_lib_ver}` in a java project?

**Comment by oehme** [comment]
Sorry I don't know what you mean by "to import deps"

**Comment by Buggaboo** [comment]
Ah, sorry, dependencies.

like these:

```java
import org.eclipse.xtend.lib.annotations.Accessors;
import org.eclipse.xtend.lib.annotations.Data;
...
```

**Comment by oehme** [comment]
You are only applying your `dependencies.gradle` script to the `buildscript` block, but not to the project. Consequently `project.ext.lib.xtend` will be null. If you used `lib.xtend`, then you would have gotten a proper error message that the property does not exist. By using the (more verbose) `project.ext.lib.xtend`, you are telling Gradle to create an empty variable if it does not exist.

**Comment by Buggaboo** [comment]
[Line 20, should do what you claim I forgot to do]([I added the compile statement in gradle like we do in Xtendroid but the java project cannot find these imports.](https://github.com/Buggaboo/xtend-j2objc-template/blob/master/allPlatforms/shared/build.gradle#L20)). Or am I mistaken?

**Comment by oehme** [comment]
You're right, didn't see that, i usually put buildscript at the very top.

Then I don't see why it wouldn't work.

**Comment by Buggaboo** [comment]
Sorry, my mistake, it's not `javac` that's complaining about the unresolved classes, it's `j2objc`.

**Comment by oehme** [comment]
The sources of Maven Central dependencies are available under the `sources` classifier, e.g.

`org.eclipse.xtend:org.eclipse.xtend.lib:2.9.1@sources`

You could declare a special dependency configuration for j2objc, so you don't pollute your main compile classpath with source jars. You could then extract a helper method which adds the main jar to your compile classpath and the source jar to the j2objc classpath.

**Comment by Buggaboo** [comment]
[Fixed!](https://github.com/Buggaboo/xtend-j2objc-template/blob/master/xtendAllPlatforms/shared/build.gradle#L45-L48)
