### ISSUE TITLE
@BundleProperty getXXX() also needs to check getArguments() == null

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#109]
If I have this fragment:

```xtend
class MyFrag extends DialogFragment {
   @BundleProperty String message

   @OnCreate
   def init() {
      if (message == null) return;
   }
}
```
then call it like so:

```xtend
  var myFrag = new MyFrag()
  myFrag.show(supportFragmentManager, "myfrag")
```

then it throws a NPE at the ```if (message == null)...``` part, because the generated ```getMessage()``` does not first check if ```getArguments() == null```.

**Comment by Buggaboo** [comment]
What is desirable?

1. Add a default ctor via `@Android*Fragment`, that sets up a `Fragment#setArguments(new Bundle)`
2. Add more boilerplate to the getters generated by `@BundleProperty` with something like
```java
if (getArguments() == null) { throw new «toJavaCode(IllegalAccessException.newTypeReference)»("Missing Bundle instance"); }
```

**Comment by tobykurien** [comment]
I was thinking ```if (getArguments() == null) { // return the default value }```

**Comment by Buggaboo** [comment]
If there _is_ a default value, iirc think I defined this for primitives.

This was back in the days, when I wrote the code without setting up a unit test :P
