### ISSUE TITLE
Strange @BundleProperty compile behaviour

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#111]
I have a class like this:

```xtend
@AndroidFragment(R.layout.fragment_network_list) class PlayerNetworkListFragment extends BaseFragment {
	enum NetworkType {
		FOLLOWING, FOLLOWER
	}
	
	@BundleProperty var Player player
	@BundleProperty var int type = NetworkType.FOLLOWER.ordinal
}
```

In Eclipse (using latest Xtendroid v0.13 code), all compiles fine and runs fine. However, compiling from gradle using the same version of Xtend (v2.9.1) results in:

```
ERROR:  PlayerNetworkListFragment.xtend - ...24: The method or field type is undefined

ERROR:  PlayerNetworkListFragment.xtend - ...29: The method or field player is undefined
``` 
These errors happen on any line where I refer to ```type``` or ```player```. No idea why - I had to remove the ```@BundleProperty``` annotation and manually code the bundle arguments to get it to compile with gradle.

**Comment by Buggaboo** [comment]
Could you write a unit test that demonstrates the bug? In `XtendroidTestCasesTest/src`, so it would't block the build. You can call it with `./gradlew :XtendroidTest:cAT`

**Comment by tobykurien** [comment]
Currently getting this error:

```
ERROR:Type mismatch: cannot convert from FragmentActivity to Activity (file:/media/truecrypt1/android/Xtendroid/XtendroidTest/src/org/xtendroid/xtendroidtest/fragments/FragmentWithLoader.xtend line : 20 column : 48)
```

**Comment by tobykurien** [comment]
Currently I get this test failure:

```
junit.framework.ComparisonFailure: expected:<> but was:<null>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at org.xtendroid.xtendroidtest.test.AndroidPreferenceAnnotation$1.run(AndroidPreferenceAnnotation.java:53)
```

**Comment by tobykurien** [comment]
Behaviour is not consistent, so closing for now.
