### ISSUE TITLE
Proposal: git submoduling xtext-android-gradle-plugin

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#112]
Hi @tobykurien ,

How do you feel about submoduling the xtext-android-gradle-plugin, to help with the testing effort?

By changing the `build.gradle`s to something like this:
```
// https://docs.gradle.org/current/userguide/custom_plugins.html#N146B7
buildscript {
    repositories {
        maven {
            url uri('../repo')
        }
    }
    dependencies {
        classpath group: 'org.gradle', name: 'customPlugin',
                  version: '1.0-SNAPSHOT'
    }
}
apply plugin: 'org.samples.greeting'
```

or instead of forcing this on our users, I could add the relevant gradle code in an outcommented form.

**Comment by tobykurien** [comment]
I don't understand. Are you suggesting adding the xtend gradle plugin to this project?

On 12 February 2016 18:24:58 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>Hi @tobykurien ,
>
>How do you feel about submoduling the xtext-android-gradle-plugin, to
>help with the testing effort?
>
>
>By changing the `build.gradle`s to something like this:
>```
>// https://docs.gradle.org/current/userguide/custom_plugins.html#N146B7
>buildscript {
>    repositories {
>        maven {
>            url uri('../repo')
>        }
>    }
>    dependencies {
>        classpath group: 'org.gradle', name: 'customPlugin',
>                  version: '1.0-SNAPSHOT'
>    }
>}
>apply plugin: 'org.samples.greeting'
>```
>
>or instead of forcing this on our users, I could add the relevant
>gradle code in an outcommented form.
>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/112

-- 
http://tobykurien.com | @tobykurien

**Comment by Buggaboo** [comment]
Yes. I'm planning on doing this (on my own machine) to test a fix for databinding issue #89.

**Comment by tobykurien** [comment]
Hmm, not sure. Worried that it would bloat the project and make compiling slower/more flaky.

On 12 February 2016 18:29:30 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>Yes. I'm planning on doing this (on my own machine) to test a fix for
>databinding issue #89.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/112#issuecomment-183398540

-- 
http://tobykurien.com | @tobykurien

**Comment by Buggaboo** [comment]
Okay, I understand. I'll start a project that submodules both :)

**Comment by Buggaboo** [comment]
I'll just do it locally then, and maybe write it up
