### ISSUE TITLE
xtendlib >=2.9.2, DuplicateFileException (during dexing)

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#114]
Add this to all your projects that rely on xtendlib:

```gradle
android {
  packagingOptions {
    // from xtendlib >=2.9.2
    exclude 'META-INF/ECLIPSE_.RSA'
    exclude 'META-INF/ECLIPSE_.SF'
  }
}
```

**Comment by dhuebner** [comment]
@Buggaboo Is there something similar to mavens -Dandroid.extractDuplicates=true in android-gradle?

See: http://simpligility.github.io/android-maven-plugin/apk-mojo.html

**Comment by Buggaboo** [comment]
I'll pass this on to Stefan @oehme .

**Comment by oehme** [comment]
I guess we should add those excludes by default in the xtext android gradle plugin. Can you open an issue there?

**Comment by Buggaboo** [comment]
[Done!](https://github.com/xtext/xtext-gradle-plugin/issues/43)
