### ISSUE TITLE
@AndroidJsonized add generated methods #equals and #hashCode

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#118]
* hashCode could be a runtime SHA-256 digest of the raw JSON String, irrespective of its parsed state
* equals is a null check and hashCode comparison

**Comment by tobykurien** [comment]
When I try to use ```@AndroidJsonized``` as per the documented example, I get this error:

```
java.lang.NullPointerException
	at
   org.xtendroid.json.JsonObjectEntry.getJsonEntries(JsonObjectEntry.xtend:30)
```

Any ideas why?

**Comment by Buggaboo** [comment]
Weird. Any of these in the chain `clazz...` could throw a NPE.

As far as I can tell, your JSON `value` looks good.

```xtend
def static Iterable<JsonObjectEntry> getJsonEntries(ClassDeclaration clazz) throws NoClassDefFoundError {
    val string = clazz.annotations.head.getValue('value').toString
```

**Comment by Buggaboo** [comment]
In hindsight, I recall that xtendlang supports a number of powerful active annotations that can automagically generate the boilerplate hashCode, equals etc. I just don't recall which one.
