### ISSUE TITLE
Split out support library dependency

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#120]
Split Xtendroid into `xtendroid` and `xtendroid-support`, where the latter can use the Android support libraries.

**Comment by Buggaboo** [comment]
The latter should be useful for projects supporting lower api levels. I always try to provide `support` friendly versions of the same implementations, but I lump them together.

We should create a new subproject, with a new manifest declaring a lower minimum api level.

**Comment by tobykurien** [comment]
@Buggaboo I've managed to remove the dependency on the support library, while still being able to support the support library! It's done using [ClassUtils](https://github.com/tobykurien/Xtendroid/blob/new_development/Xtendroid/src/org/xtendroid/utils/ClassUtils.xtend) to search the hierarchy of a class using reflection and string comparisons instead of instantiating types. For example, [here's](https://github.com/tobykurien/Xtendroid/blob/new_development/Xtendroid/src/org/xtendroid/adapter/AndroidViewHolder.xtend#L47) how I support the ```RecyclerView```.

There's one thing I cannot fix though, which is the [BgLoader](https://github.com/tobykurien/Xtendroid/blob/new_development/Xtendroid/src/org/xtendroid/utils/BgLoader.xtend) which was importing the support version of the ```AsyncTaskLoader``` class, which I have changed to the non-support version. Not sure what the best fix for this is...

**Comment by Buggaboo** [comment]
Hiya, good job!

BgLoader contains two implementations iirc, `BgSupportLoader?` and `BgLoader`, these can be separated right?

I'm totally buried by work atm, I can't join you right now in tidying up.

Thanks!

**Comment by tobykurien** [comment]
Yes, but we would then need a whole other project and artifact for the version with support library, e.g. xtendroid-support. Seems like a lot of trouble for just the Loader...

On 14 February 2017 20:07:50 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>Hiya, good job!
>
>BgLoader contains two implementations iirc, `BgSupportLoader?` and
>BgLoader, these can be separated right?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/120#issuecomment-279787045

-- 
tobykurien.com | @tobykurien

**Comment by Buggaboo** [comment]
To be honest, with the advent of okhttp, volley, etc. I don't think anyone uses Loaders anymore in combination with network i/o, which was one of its purposes, back in the days.

I think it's actually easier to use your own Looper anchored to the Application (singleton) to queue (incoming) messages, and deliver them when there is a context object, from `onResume`.
Or some other thread pooling + message publishing mechanism, that doesn't depend on the Context altogether.

I won't mind if you dropped the implementation altogether, i.e. `git rm ...`.

I can look at it later if you want, in about 6 months...

I don't know what our users want though... although sometimes I think we two are the only end-users.

**Comment by tobykurien** [comment]
That's not necessary because the current implementation works with the standard Loader. I have adjusted the FragmentWithLoader example.

On 14 February 2017 20:34:10 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>To be honest, with the advent of okhttp, volley, etc. etc. I don't
>think anyone uses Loaders anymore in combination with network i/o.
>
>I think it's actually easier to use your own Looper anchored to the
>Application (singleton) to queue (incoming) messages, and deliver them
>when there is a context object, from `onResume`.
>
>I won't mind if you dropped the implementation altogether, i.e. `git rm
>...`.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/120#issuecomment-279794247

-- 
tobykurien.com | @tobykurien
