### ISSUE TITLE
@AndroidJson to return default value if set, rather than throw exception

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#121]

**Comment by Buggaboo** [comment]
Btw, @tobykurien, do you mean `@AndroidJson` or `@AndroidJsonized`?

Because I recall that I already supported default values for `@AndroidJson`?

If so, could you check out the opt<generated getter>?

**Comment by tobykurien** [comment]
I did mean ```@AndroidJson```, but I'll check again with your latest changes and revert.

**Comment by tobykurien** [comment]
Issue is still there, see modified JsonTest, which fails with:

```
org.json.JSONException: No value for doesNotExistInJson
```
Instead of returning the default value of 1.

**Comment by tobykurien** [comment]
I think it would be better to add a try/catch around the json getter when there is a default value, and return the default value the case of an exception, rather than adding the optXXX methods or additional annotations. The default value is already starting that the field is optional.

On 9 June 2016 23:42:09 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>I *fixed* the issue on `@A..Jsonized` :) by adding an `opt`blah
>functions.
>
>I'm planning on doing the same with the `@AndroidJson` (original), by
>also adding `opt` methods, or add a whole new annotation altogether,
>e.g. `@OptJson`? Your thoughts?
>
>The default value issue must be fixed though, with unit tests, I agree.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/121#issuecomment-225035665

-- 
http://tobykurien.com | @tobykurien

**Comment by Buggaboo** [comment]
Oh, that sounds good to me. I can do it around next week, unless someone feels a stronge urge to scratch that itch.

**Comment by Buggaboo** [comment]
Instead of catching an JSONException, that could cause more damage along the way by casting too wide a net. I simply check `JSONObject#isNull`, if this returns true, then either the attr is missing or the value is actually `null`, then and only then I return the default value.

**Comment by tobykurien** [comment]
This sounds good but I wonder about the behaviour when the attribute exists and is set to null in the JSON - in this case should we not return null rather than the default value?

On 22 June 2016 18:14:11 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>Instead of catching an JSONException, that could cause more damage
>along the way by casting too wide a net. I simply check
>`JSONObject#isNull`, if this returns true, then either the attr is
>missing or the value is actually `null`, then and only then I return
>the default value.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/121#issuecomment-227795611

-- 
http://tobykurien.com | @tobykurien

**Comment by Buggaboo** [comment]
I don't know if we should return `null` for scalar primitive values.

**Comment by tobykurien** [comment]
Yes default values for scalar and null of objects, emtpy arrays for arrays?

On 23 June 2016 13:05:05 GMT+02:00, Jasm Sison <notifications@github.com> wrote:
>I don't know if we should return `null` for scalar primitive values.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/Xtendroid/issues/121#issuecomment-228017453

-- 
http://tobykurien.com | @tobykurien

**Comment by Buggaboo** [comment]
It's hard for me to decide when or why our users will use the non-null default, or null.

So far, I decided that the user can pre-initialize a field with `null` or some other type of object, e.g. primitive or some composite type like itself, in the case that this isn't defined, for (aggregate) primitives we throw a JSONException, for all other types we just return `null`.

The mapping from one value to another isn't quite clear cut, since we also support aggregate types, i.e. `List<?>` and arrays.

 I don't want to over-engineer this.

Please see commit 9ecffc7a5ab60843e8b9aa6f5c1e69cce3a6b987.

**Comment by tobykurien** [comment]
This test is now passing :)
