### ISSUE TITLE
Xtendroid test issues

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#129]
Running ```./gradlew XtendroidTest:cC``` fails to compile currently. The error output from gradle is so massive it doesn't even fit in the terminal scroll buffer, so hard to figure out what's going on.

**Comment by tobykurien** [comment]
So, running ```./gradlew XtendroidTest:assembleDebug``` first, and then ```./gradlew XtendroidTest:connectedCheck``` seems to move things along a little bit. Then you get this gem of an error:

```
/Xtendroid/XtendroidTest/build/generated/source/xtend/debugAndroidTest/org/xtendroid/xtendroidtest/test/Defaults.java:101: error: illegal character: '#'
    if (_jsonObj.isNull("listOfInts")) return #[ 0, 1, 2 ];
```

**Comment by tobykurien** [comment]
Soldiering on. Had to comment out stuff in JsonTest (https://github.com/tobykurien/Xtendroid/commit/fd2869851c202a558bf9c4e810da46a5c6a85221) to get tests to run again, you might want to look into this @Buggaboo

**Comment by tobykurien** [comment]
FYI @Buggaboo there are test failures in ```JsonizedTest```. I added the ```run_specific_test.sh``` script to make testing from command line easier, e.g. ```./run_specific_test.sh JsonizedTest``` will reveal the failing tests.

**Comment by Buggaboo** [comment]
Okay, I'll go and check it out

**Comment by Buggaboo** [comment]
A new release will be out soon, with a fix for the packagingOptions thing and connected tests! @oehme right?

**Comment by oehme** [comment]
Yep, 1.0.13 is in the making.

**Comment by tobykurien** [comment]
Working great now!
