### ISSUE TITLE
@BeanAdapter doesn't work with the new AppCompat wrapper classes

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#130]

**Comment by Buggaboo** [comment]
```
java.lang.NoClassDefFoundError: org.xtendroid.adapter.BeanAdapter$3
at org.xtendroid.adapter.BeanAdapter.setupMapping(BeanAdapter.xtend:88)
```

It's a reflection issue.

**Comment by tobykurien** [comment]
So that's something unrelated. What I was referring to is that ```BeanAdapter``` works on ```EditText``` for example, but nowadays the ```EditText``` widget gets wrapped by an ```AppCompatEditText``` so ```BeanAdapter``` needs to work for any subclass of the widgets it currently supports.
