### ISSUE TITLE
Incompatible with Android Studio

### ISSUE THREAD

**Issue by oehme** [tobykurien/Xtendroid#62]
I just tried out xtendroid with our Xtend prototype for Intellij. There are 2 issues why it won't work

- there are hardcoded paths in the processor, which don't match the new layout. You should at least check src/main/res. In Xtend 2.8 there will be a getSourceFolders method :)

- The bigger issue: We can't load annotation processors from aar archives inside the IDE. You also need to provide a plain old jar on maven central. This will also make it easier to consume for eclipse users.

While you're at it: Please also split the extension methods from the annotation processors into two jars. The latter are only needed at compile time and just bloat the runtime classpath on the device. Keep in mind they pull in the macro library that might increase in size when we add full expression support in the future.

**Comment by Buggaboo** [comment]
I'm really looking forward to fixing those issues :)

**Comment by tobykurien** [comment]
@Buggaboo you can start now, see this thread for details: https://groups.google.com/forum/#!topic/xtend-lang/3zXH2rByVkw

**Comment by Buggaboo** [comment]
I installed the following plugins, by adding this [snapshot repository url](https://hudson.eclipse.org/xtext/job/xtext-intellij/lastSuccessfulBuild/artifact/git-repo/intellij/build/intellijRepository/updatePlugins.xml) in AS 1.0.3:

* xtext
* sdomain (probably not useful)
* example (also unlikely to be useful, for our purposes)
* xbase

I found your comment on getting the Xtendroid jar to work on AS:

> It's not on Maven Central, but grab it here: https://github.com/tobykurien/Xtendroid/raw/v0.12_development/Xtendroid/release/xtendroid_v0.12_SNAPSHOT.jar
> Drop it into /libs and add that to your build.gradle:
 
> compile fileTree(dir: 'libs', include: ['*.jar'])

**Comment by oehme** [comment]
You need xtext, xbase and *xtend*

**Comment by tobykurien** [comment]
@Buggaboo try checking out this skeleton project and try it (I am also in Ubuntu): https://github.com/tobykurien/XtendApp

**Comment by Buggaboo** [comment]
Okay, thanks.

**Comment by tobykurien** [comment]
@Buggaboo is it just me, or does the Xtend editor still not work on Android Studio with Xtendroid? I've followed the procedure in the wiki (https://github.com/tobykurien/Xtendroid/wiki/HowTo-setup-Android-Studio-%28aka-Intellij%29-support) but if I open ```MainActivity.xtend``` for example, it's full of errors, although the project compiles fine.

**Comment by Buggaboo** [comment]
Yeah, the Xtend editor leaves a lot to be desired... it does give me a truckload of false positives as well.

**Comment by mikemee** [comment]
:+1:  for AS support (in any version). Although I've mostly used Eclipse for Android development, the love is definitely being shown to AS and it's becoming noticeably harder to get others to work on projects when they have to use Eclipse. It's keeping me back from really getting into Xtend unfortunately.

Happy to help with any how-tos / general guides if/when the need arises. Thanks for all the amazing work on this!

**Comment by Buggaboo** [comment]
@mikemee Please check out v0.13, and use that in concert with intellij IDEA >=15 and/or AS >=2.0
The team has been working hard to drag Xtendroid to the intellij camp.

Just import the projects via the default gradle files.
