### ISSUE TITLE
@BundleProperty not working to retrieve value

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#65]
I declared a ```@BundleProperty``` in a fragment, set the value by calling ```Fragment.putMyProperty(...)```, and then passed the bundle as arguments to the fragment, but in the fragment, the value I get back is always the default value.

**Comment by Buggaboo** [comment]
Hm. I'll look into it. Thanks for reporting.

**Comment by Buggaboo** [comment]
Aha. I did something stoooopid. You used an int right?

I foresee a patch coming really soon. :)
