### ISSUE TITLE
Feature idea @AndroidMenu: request for comments

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#70]
Looking over the code gave me a new idea for an annotation, @AndroidMenu
if you slap `@AndroidMenu(R.menu.the_greatest_menu_ever)` on an Activity or Fragment, 
it generates the inflation stuff and generates your MenuItem accessors.

Or... we can extend @AndroidActivity and @AndroidFragment to support this:

```java
@AndroidActivity(layout=R.layout.l, menu=R.menu.m)
class MyActivity...

@AndroidFragment(layout=R.layout.l, menu=R.menu.m)
class MyFragment... // the fragment's onOptionsItemSelected must be passed to the activity's
```

If you slap `@AndroidMenu(R.id.the_greatest_item)` on a method,
then this will injected in the switch in the inflation method.

Comments?

**Comment by tobykurien** [comment]
I do like the idea of adding ```menu=R.menu....```, however it feels like building fucntionality for the sake of building functionality. Inflating a menu and responding to items selected is like 4 lines of fairly straight-forward code (especially in a fragment, which is typically where this is handled).

**Comment by Buggaboo** [comment]
Good point. :) I vote for minimalism.
