### ISSUE TITLE
Can't use Xtendroid with Xtend 2.8.0

### ISSUE THREAD

**Issue by maannajjar** [tobykurien/Xtendroid#73]
Hello,
I have been using Xtendroid as a library project with xtend 2.7.3. However, I downloaded the new Eclipse/Xtend 2.8.0 bundle and now Xtendroid doesn't work anymore. The annotations are recognized by the compiler but they don't have any effect in generated files. View getters are not generated, onCreate is not created, callback files are not there,..etc.  I switched to v0.12_development branch but the same problem exist.. This could be an xtend issue but I'm maybe missing something ?

**Comment by oehme** [comment]
Hey there,

we need some additional information to help you:

- is there an error marker on the annotation, if so, what is the error?
- are there any errors in the error log (Window->Show View -> Error log)
- an example file or project would be great

**Comment by tobykurien** [comment]
@maannajjar I pushed a commit yesterday that should fix the problem. It is on the development branch. Could you try cleaning the projects, and use Xtend v2.8.1?

**Comment by tobykurien** [comment]
@maannajjar I've updated the v0.12 snapshot here https://github.com/tobykurien/Xtendroid/blob/v0.12_development/Xtendroid/release/xtendroid_v0.12_SNAPSHOT.jar

I've used that successfully to compile a project under Xtend 2.8.1. Please give that a try and let me know if it works?

**Comment by maannajjar** [comment]
Hey @tobykurien @oehme 

I used the snapshot and it worked in 2.8.0. However, after updating to 2.8.1, using Xtendroid as a library project is working normally again. It seems like this was an issue in 2.8.0.
