### ISSUE TITLE
[suggestion] Handle options menu

### ISSUE THREAD

**Issue by PerfectCarl** [tobykurien/Xtendroid#78]
At the moment, there is no **xtended way** to define and intercept event for option menus.

This would be a great addition to xtendroid

**Comment by tobykurien** [comment]
This was mentioned before, see issue #70

**Comment by PerfectCarl** [comment]
I see. 
I still prefer the declarative way other the procedural approach.

I subscribed to the original ticket if one day you revisit this issue,
