### ISSUE TITLE
Get Xtendroid to work on Intellij IDEA 15 CE

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#84]
I'm not a groovy/gradle expert. @tobykurien do you have any advice on where/how to start?

**Comment by tobykurien** [comment]
In theory, apart from installing the Xtend plugin for gradle, the gradle setup should be exactly as before (as per XtendApp). Try these dependencies:

```
android {
  ...
  dependencies {
      ...
      compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.8.3'
      compile 'com.github.tobykurien:xtendroid:0.12.1'  
  }
}
```

**Comment by svenefftinge** [comment]
You should bump the plug-in version if you haven't already.

classpath 'org.xtend:xtend-android-gradle-plugin:0.4.8'


2015-11-10 6:59 GMT+01:00 Toby Kurien <notifications@github.com>:

**Comment by Buggaboo** [comment]
Okay, now we have the project working ([dev branch v0.13](https://github.com/tobykurien/Xtendroid/compare/v0.13_development)) under android studio 2.0 and intellij idea 15. I'd like to address the remaining issues:
1. Duplicated gradle dependency versioning everywhere
2. Duplicated build instructions (see examples)
3. Fix the broken test (sub)project, `:XtendroidTestCasesTest`

The first two issues can be solved by importing an external gradle file. See [ext method](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html) and [this](http://stackoverflow.com/questions/9547170/in-gradle-how-do-i-declare-common-dependencies-in-a-single-place). Which means we should upgrade to gradle 2.9.

I already started work on this:

**dependencies.gradle**
```gradle
ext {
    android_gradle_ver = '1.3.1'
    xtend_gradle_ver = '0.4.12'

    build = [
        android_gradle : "com.android.tools.build:gradle:${android_gradle_ver}",
        xtend_android_gradle : "org.xtend:xtend-android-gradle-plugin:${xtend_gradle_ver}",
        xtend_gradle : "org.xtend:xtend-gradle-plugin:${xtend_gradle_ver}"
    ]

    xtend_lib_ver = '2.9.+'
    android_sdk_support_ver = '23.1.1'

    lib = [
        xtend : "org.eclipse.xtend:org.eclipse.xtend.lib:${xtend_lib_ver}",
        android : [
                support_v4 : "com.android.support:support-v4:${android_sdk_support_ver}",
                appcompat_v7 : "com.android.support:appcompat-v7:${android_sdk_support_ver}"
        ]
    ]
}
```

I need help with the XtendTest and XtendTestCasesTest (3rd issue). XtendTest should be built as two flavours (i.e. com.android.library), as a lib for XtendTest, and in the future as a dep for robotium, robolectric etc. and as an application (i.e. com.android.application).

**Comment by tobykurien** [comment]
Can we hold off on moving this project into Android Studio for a bit? Because:

- Let's at least wait till AS 2 hit beta or stable
- There's no need for this particular project to be in AS, since I anyway prefer using Eclipse for it. Only the projects using Xtendroid (like XtendApp) need to move to AS
- I'd like to spend some time figuring out how best to re-structure the project, so that it works both in AS and Eclipse. I don't yet want to break Eclipse compatibility here
- I'd like to split the samples out into a separate project, and that project can then also move to AS

**Comment by Buggaboo** [comment]
I'd like to support both IDEs. I'm fine with waiting, until everything matures a bit. I'll do the first two issues, this has no impact on the third. You saw the `project(:meh)...` trick right in `settings.gradle`, right? You can rearrange the projects anyway you like.

**Comment by tobykurien** [comment]
Is this working now? Can we close this issue?

**Comment by Buggaboo** [comment]
We completely support AS and intellij and gradle. This can be closed. Thanks.

**Comment by tobykurien** [comment]
Woohoo!
