### ISSUE TITLE
@BundleProperty breaks when using a Parcelable

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/Xtendroid#98]
Error is: 

```
The method put(String, Parcelable) is undefined for the type Bundle
```

Which it is - that should be ```putParcelable(String, Parcelable)```

**Comment by Buggaboo** [comment]
Fixed. Patch coming up soon.

**Comment by tobykurien** [comment]
Works like a charm, thanks! I'm loving this annotation :+1:
